### ISSUE TITLE
Generated `#[deny(safe_packed_borrows)]` is not compatible with `#![forbid(future_incompatible)]`

### ISSUE THREAD

**Issue by yoshuawuyts** [taiki-e/pin-project#281]
The compiler's built-in `#[deny(future_incompatible)]` seems to be incompatible with `pin-project-internal`. It seems `#[deny(safe_packed_borrows)]` will be disallowed in the future, but `pin-project` generates code that uses that lint under certain circumstances. Given the Rust 2021 edition may turn all 2018 warnings into errors, this may become a problem.

I'm not exactly sure what triggers this, but adding the lint to the current main of [tide](https://github.com/http-rs/tide) surfaces the error. Though I feel I've seen this happen before when working on other crates. I'm not sure what the right outcome here is, but thought it might be important enough to raise. Thanks!

https://github.com/taiki-e/pin-project/pull/34 seems related.

## Screenshot

![Screenshot 2020-09-26 19 20 16](https://user-images.githubusercontent.com/2467194/94346521-72885e00-002d-11eb-89d7-e7b70f5c3878.png)

**Comment by Aaron1011** [comment]
It looks like you're actually using `pin_project_lite`.

This looks like a bug in rustc - it's emitting an error about [this `#[deny(safe_packed_borrows)]`](https://github.com/taiki-e/pin-project-lite/blob/9579d1e64657b40fa9887c562d4f1892d0a24551/src/lib.rs#L288) getting 'overruled'. I think that error is only supposed to occur when a `#[warn]` or `#[allow]` get overruled.

**Comment by Aaron1011** [comment]
I think it would be fine for `pin-project-lite` to use `#[forbid]`, though.

**Comment by taiki-e** [comment]
I definitely do not recommend using `forbid` on the lints other than `unsafe_code` lint. They will constant improvement/change, and code that was not warned at the release time may become unavailable. Especially for lint groups like `future_incompatible`, it's possible that a new lint will be added.

That said, as @Aaron1011 said, this can be easily fixed by switching `#[deny(safe_packed_borrows)]` to `#[forbid(safe_packed_borrows)]`, so I'll do that.

---
> This looks like a bug in rustc - it's emitting an error about [this `#[deny(safe_packed_borrows)]`](https://github.com/taiki-e/pin-project-lite/blob/9579d1e64657b40fa9887c562d4f1892d0a24551/src/lib.rs#L288) getting 'overruled'. I think that error is only supposed to occur when a `#[warn]` or `#[allow]` get overruled.

I guess this is intentional behavior, as it should be possible to allow lint in scopes where lint is denied, but it's certainly not intuitive...

**Comment by taiki-e** [comment]
Fixed in pin-peoject 0.4.24 and pin-project-lite 0.1.8

**Comment by yoshuawuyts** [comment]
> They will constant improvement/change, and code that was not warned at the release time may become unavailable.

I hadn't given this enough thought, and you're absolutely right. I'll have to revise this. Thank you!
