### ISSUE TITLE
Consider merging this crate and pin-utils

### ISSUE THREAD

**Issue by Aaron1011** [taiki-e/pin-project#58]
The [pin-utils](https://github.com/rust-lang-nursery/pin-utils) crate provides three macros: `pin_mut`, `unsafe_pinned`, and `unsafe_unpinned`.

The `#[pin_project]` attribute provided by this crate is strictly more powerful than `unsafe_pinned` and `unsafe_unpinned` - it ensures safety by default, but lets you opt-out via `unsafe` to get the unchecked behavior of `unsafe_pinned` and `unsafe_unpinned`.

The only thing this crate is missing is the `pin_mut` macro, which is a small `macro_rules!` macro.

I think it would be useful for there to be a single crate which handles all of these pinning operations. Currently, users that want both safe pin projections and stack pinning need to use two separate crates.

**Comment by taiki-e** [comment]
> I think it would be useful for there to be a single crate which handles all of these pinning operations. Currently, users that want both safe pin projections and stack pinning need to use two separate crates.

I agree with you. I submitted https://github.com/rust-lang-nursery/futures-rs/pull/1686 for this, but, we can consider redefining in pin-project.

**Comment by taiki-e** [comment]
cc @Nemo157 Any thoughts on this?

**Comment by Nemo157** [comment]
I actually find `pin_mut!` quite annoying to use in practice because of the extra binding needed (I fall into the “less having to think of names is better” camp, so commonly the thing that needs pinning is something that I wouldn’t normally bind to a variable). When I last wrote some code that involved a lot of pinning I threw together [this crate](https://github.com/Nemo157/ergo-pin-rs) as an experiment in better ergonomics, but I didn’t get around to actually publishing it.

**Comment by taiki-e** [comment]
> I actually find `pin_mut!` quite annoying to use in practice because of the extra binding needed (I fall into the “less having to think of names is better” camp, so commonly the thing that needs pinning is something that I wouldn’t normally bind to a variable).

Yeah, I also feel `pin_mut!` is not ergonomic (nevertheless, I added it to futures 😁.).

> When I last wrote some code that involved a lot of pinning I threw together [this crate](https://github.com/Nemo157/ergo-pin-rs) as an experiment in better ergonomics, but I didn’t get around to actually publishing it.

As long as you look at [the code in the tests directory](https://github.com/Nemo157/ergo-pin-rs/blob/master/tests/multi_evaluated_expressions.rs), it looks like it's easy to use...

**Comment by taiki-e** [comment]
The ergonomic API for stack pinning has not been established yet, so if adding these support to `pin-project` at this time, I think it needs to add unergonomic `pin_mut` to keep stability.

And if we want to experiment with ergonomic things, I think it should be done in another library.

**Comment by LucioFranco** [comment]
Can we not add pin_mut at a later time or what ever the "ergo" api will be. Don't think I've needed pin_mut where I have pin-project and not futures-util?

**Comment by Nemo157** [comment]
Small update to my comment above, I've now published [`ergo-pin`](https://docs.rs/ergo-pin). My primary reason for writing that was while experimenting with pinning collections and pinned iterators (to allow using generators to create an iterator), so that was a usecase where I could have been using `pin-project` (although wasn't) and be completely outside the futures ecosystem.

**Comment by taiki-e** [comment]
Actually, `futures_util::pin_mut`/`futures::pin_mut` are sufficient for my use-case and I'm also interested in trying `ergo-pin`, but I don't have a strong opinion about whether to do this on `pin-project` or `pin-utils` itself.

**Comment by taiki-e** [comment]
I'm still torn about this. Here are some updates and my opinions (TL;DR: I feel there are one advantage and some relatively minor drawbacks):
  * I'm now a maintainer of pin-utils.
  * pin-utils will only provide stack-pinning util in the future (https://github.com/rust-lang/pin-utils/issues/29)
  * There are two pin-project crates, and the decision here is also propagated to [lite](https://github.com/taiki-e/pin-project-lite).
  * Adding a futures-util dependency for use only a stack pinning utility is not good. (However, as pin-project and dependencies require relatively long compile times, "add pin-project dependency for use only a stack pinning utility" may not happen very often.)
  * I think after removed the project attributes (#225) should allow the API to be considered stable enough (i.e., v1.0). Not so when adding stack pinning API.
  * pin-utils is a really small crate that won't impact compile time with or without merging. (Depending on the situation, but using pin-project's stack pinning utility instead of pin-utils should increase overall compile time because pin-project is only compiled after proc-macro is compiled. But I feel some users are more sensitive to the increasing number of dependencies than the actual compile time.)
  * It's convenient to have all pin related utilities in one place.
  * If we don't add this, the name of pin-project is descriptive about what this crate does.

**Comment by Aaron1011** [comment]
I'm relatively indifferent about adding `pin_mut` to this crate. However, I think it would be a good idea to reach a decision one way or the other, as this is the only remaining open issue :smile:

**Comment by taiki-e** [comment]
I'm going closing this because the benefits of doing this don't seem to outweigh the drawbacks I said in the comment above, at this time. 

If anyone can explain more about the benefits of doing this, we can reopen it.
